export enum TranslatesEnum {
  CHANGE_LANGUAGE = 'changeLanguage',
  CRACK_THE_CODE = 'crackTheCode',
  GUESS_THE_NUMBER = 'guessTheNumber',
  SIMON = 'simon',
  ROUTES = 'routes',
  PARAMS = 'params',
  NETWORKS = 'networks',

  CRACK_THE_CODE_START_GAME = 'crackTheCodeStartGame',
  CRACK_THE_CODE_TITLE = 'crackTheCodeTitle',
  CRACK_THE_CODE_RESTART_GAME = 'crackTheCodeRestartGame',
  CRACK_THE_CODE_RESUME_GAME = 'crackTheCodeResumeGame',
  CRACK_THE_CODE_PAUSE_GAME = 'crackTheCodePauseGame',
  CRACK_THE_CODE_SECRET_CODE_LABEL = 'crackTheCodeSecretCodeLabel',
  CRACK_THE_CODE_ATTEMPTS_LABEL = 'crackTheCodeAttemptsLabel',
  CRACK_THE_CODE_INPUT_PLACEHOLDER = 'crackTheCodeInputPlaceholder',
  CRACK_THE_CODE_GUESS_ALREADY_TRIED = 'crackTheCodeGuessAlreadyTried',
  CRACK_THE_CODE_SUBMIT_GUESS = 'crackTheCodeSubmitGuess',
  CRACK_THE_CODE_ATTEMPTS_HISTORY_LABEL = 'crackTheCodeAttemptsHistoryLabel',
  CRACK_THE_CODE_CORRECT_PLACE_LABEL = 'crackTheCodeCorrectPlaceLabel',
  CRACK_THE_CODE_WRONG_PLACE_LABEL = 'crackTheCodeWrongPlaceLabel',
  CRACK_THE_CODE_GAME_WON_MESSAGE = 'crackTheCodeGameWonMessage',
  CRACK_THE_CODE_INSTRUCTIONS = 'crackTheCodeInstructions',

  GUESS_THE_NUMBER_START_GAME = 'guessTheNumberStartGame',
  GUESS_THE_NUMBER_TITLE = 'guessTheNumberTitle',
  GUESS_THE_NUMBER_RESTART_GAME = 'guessTheNumberRestartGame',
  GUESS_THE_NUMBER_RESUME_GAME = 'guessTheNumberResumeGame',
  GUESS_THE_NUMBER_PAUSE_GAME = 'guessTheNumberPauseGame',
  GUESS_THE_NUMBER_SECRET_CODE_LABEL = 'guessTheNumberSecretCodeLabel',
  GUESS_THE_NUMBER_ATTEMPTS_LABEL = 'guessTheNumberAttemptsLabel',
  GUESS_THE_NUMBER_INPUT_PLACEHOLDER = 'guessTheNumberInputPlaceholder',
  GUESS_THE_NUMBER_GUESS_ALREADY_TRIED = 'guessTheNumberGuessAlreadyTried',
  GUESS_THE_NUMBER_SUBMIT_GUESS = 'guessTheNumberSubmitGuess',
  GUESS_THE_NUMBER_ATTEMPTS_HISTORY_LABEL = 'guessTheNumberAttemptsHistoryLabel',
  GUESS_THE_NUMBER_IS_EQUAL_LABEL = 'guessTheNumberIsEqualLabel',
  GUESS_THE_NUMBER_IS_LESS_LABEL = 'guessTheNumberIsLessLabel',
  GUESS_THE_NUMBER_IS_GREATER_LABEL = 'guessTheNumberIsGreaterLabel',
  GUESS_THE_NUMBER_GAME_WON_MESSAGE = 'guessTheNumberGameWonMessage',
  GUESS_THE_NUMBER_INSTRUCTIONS = 'guessTheNumberInstructions',

  MEMORY = 'memory',
  MEMORY_TITLE = 'memoryTitle',
  MEMORY_START_GAME = 'memoryStartGame',
  MEMORY_RESTART_GAME = 'memoryRestartGame',
  MEMORY_PAUSE_GAME = 'memoryPauseGame',
  MEMORY_RESUME_GAME = 'memoryResumeGame',
  MEMORY_ATTEMPTS_LABEL = 'memoryAttemptsLabel',
  MEMORY_GAME_WON_MESSAGE = 'memoryGameWonMessage',
  MEMORY_INSTRUCTIONS = 'memoryInstructions',

  SIMON_TITLE = 'simonTitle',
  SIMON_START_GAME = 'simonStartGame',
  SIMON_RESTART_GAME = 'simonRestartGame',
  SIMON_PAUSE_GAME = 'simonPauseGame',
  SIMON_RESUME_GAME = 'simonResumeGame',
  SIMON_LEVEL = 'simonLevel',
  SIMON_GAME_OVER = 'simonGameOver',
  SIMON_SOUND_ENABLED = 'simonSoundEnabled',
  SIMON_INSTRUCTIONS = 'simonInstructions',
}
