export enum TranslatesEnum {
  CHANGE_LANGUAGE = 'changeLanguage',
  CRACK_THE_CODE = 'crackTheCode',
  ROUTES = 'routes',
  PARAMS = 'params',
  NETWORKS = 'networks',
  CRACK_THE_CODE_START_GAME = 'crackTheCodeStartGame',
  CRACK_THE_CODE_TITLE = 'crackTheCodeTitle',
  CRACK_THE_CODE_RESTART_GAME = 'crackTheCodeRestartGame',
  CRACK_THE_CODE_SECRET_CODE_LABEL = 'crackTheCodeSecretCodeLabel',
  CRACK_THE_CODE_ATTEMPTS_LABEL = 'crackTheCodeAttemptsLabel',
  CRACK_THE_CODE_INPUT_PLACEHOLDER = 'crackTheCodeInputPlaceholder',
  CRACK_THE_CODE_GUESS_ALREADY_TRIED = 'crackTheCodeGuessAlreadyTried',
  CRACK_THE_CODE_SUBMIT_GUESS = 'crackTheCodeSubmitGuess',
  CRACK_THE_CODE_ATTEMPTS_HISTORY_LABEL = 'crackTheCodeAttemptsHistoryLabel',
  CRACK_THE_CODE_CORRECT_PLACE_LABEL = 'crackTheCodeCorrectPlaceLabel',
  CRACK_THE_CODE_WRONG_PLACE_LABEL = 'crackTheCodeWrongPlaceLabel',
  CRACK_THE_CODE_GAME_WON_MESSAGE = 'crackTheCodeGameWonMessage',
}
